version: '3.7'
services:

  users_api:
    container_name: users_api
    build:
      context: ./users_api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      init:
        condition: service_completed_successfully

  init:
    container_name: init
    build:
      context: ./init
      dockerfile: Dockerfile
    networks:
      - arch-network
    depends_on:
      postgres:
        condition: service_healthy



  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=ismail
      - POSTGRES_PASSWORD=ismail
      - PGDATA=/data/postgres
      - POSTGRES_DB=shop_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"
    external: false
